# Generated by Django 5.2.5 on 2026-01-13 17:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("user", "Пользователь"),
                            ("product", "Товар"),
                            ("category", "Категория"),
                            ("order", "Заказ"),
                            ("cart", "Корзина"),
                            ("review", "Отзыв"),
                            ("permission", "Право доступа"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Название элемента",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание элемента"),
                ),
            ],
            options={
                "verbose_name": "Бизнес-элемент",
                "verbose_name_plural": "Бизнес-элементы",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("customer", "Покупатель"),
                            ("guest", "Гость"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Название роли",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание роли"),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                (
                    "read_permission",
                    models.BooleanField(default=False, verbose_name="Чтение своих"),
                ),
                (
                    "read_all_permission",
                    models.BooleanField(default=False, verbose_name="Чтение всех"),
                ),
                (
                    "create_permission",
                    models.BooleanField(default=False, verbose_name="Создание"),
                ),
                (
                    "update_permission",
                    models.BooleanField(
                        default=False, verbose_name="Редактирование своих"
                    ),
                ),
                (
                    "update_all_permission",
                    models.BooleanField(
                        default=False, verbose_name="Редактирование всех"
                    ),
                ),
                (
                    "delete_permission",
                    models.BooleanField(default=False, verbose_name="Удаление своих"),
                ),
                (
                    "delete_all_permission",
                    models.BooleanField(default=False, verbose_name="Удаление всех"),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="authorization.businesselement",
                        verbose_name="Бизнес-элемент",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="authorization.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило доступа",
                "verbose_name_plural": "Правила доступа",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="authorization.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя",
                "verbose_name_plural": "Роли пользователей",
            },
        ),
    ]
