# Generated by Django 5.2.5 on 2026-01-13 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("success", models.BooleanField(default=False, verbose_name="Успешно")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина неудачи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка входа",
                "verbose_name_plural": "Попытки входа",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен подтверждения email",
                "verbose_name_plural": "Токены подтверждения email",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен сброса пароля",
                "verbose_name_plural": "Токены сброса пароля",
            },
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                            ("verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=20,
                        verbose_name="Тип токена",
                    ),
                ),
                (
                    "token",
                    models.TextField(verbose_name="Токен (хешированный для refresh)"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает в")),
                (
                    "is_blacklisted",
                    models.BooleanField(default=False, verbose_name="В черном списке"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен аутентификации",
                "verbose_name_plural": "Токены аутентификации",
                "indexes": [
                    models.Index(
                        fields=["user", "token_type"],
                        name="authenticat_user_id_706910_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_5ea618_idx"
                    ),
                    models.Index(
                        fields=["is_blacklisted"], name="authenticat_is_blac_fb95a1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Ключ сессии"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает в")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия",
                "verbose_name_plural": "Сессии",
                "indexes": [
                    models.Index(
                        fields=["session_key"], name="authenticat_session_844b9b_idx"
                    ),
                    models.Index(
                        fields=["user", "expires_at"],
                        name="authenticat_user_id_f459b3_idx",
                    ),
                ],
            },
        ),
    ]
